services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: sqs
      LOCALSTACK_HOST: 0.0.0.0
      TZ: Europe/London
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: cat /tmp/ready
      interval: 5s
      start_period: 5s
      retries: 10

  decision-deriver:
    build:
      args:
        DEFRA_NUGET_PAT: ${DEFRA_NUGET_PAT}
    ports:
      - '8080:8080'   
    depends_on:
      localstack:
        condition: service_healthy
      wiremock:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ENVIRONMENT: local
      PORT: 8080
      DataApi__BaseAddress: "http://wiremock"
      DataApi__Password: "secret"
      SQS_Endpoint: http://localstack:4566
      AWS_EMF_ENVIRONMENT: Local
  
  wiremock:
    environment:
      TZ: Europe/London
    image: sheyenrath/wiremock.net:latest
    ports:
      - "9090:80"
