name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4      
        
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "compose.yml"
          
      - name: Wait for Localstack
        run: ./trade-imports-decision-deriver/wait-for-docker-logs.sh sns-sqs-emulator "Ready." 60
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0
      - name: Update NuGet.config
        run: |
          dotnet nuget remove source defra
          dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name defra "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --configfile NuGet.config
      - name: Test
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0
      - run: dotnet test
      - name: Check Dockerfile Builds
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: trade-imports-decision-deriver:latest
      - name: Check with Trivy
        run: docker run -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image trade-imports-decision-deriver:latest --ignore-unfixed
  sonarcloud-scan:
    name: CDP SonarCloud Scan
    uses: ./.github/workflows/sonarcloud.yml
    needs: pr-validator
    secrets: inherit
